global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MastroHub Application
  - job_name: 'mastrohub-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker:9323']

  # Custom application metrics
  - job_name: 'mastrohub-metrics'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # API endpoints health check
  - job_name: 'api-health'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/health'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Database performance
  - job_name: 'database-performance'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Cache performance
  - job_name: 'cache-performance'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Load balancer metrics
  - job_name: 'nginx-metrics'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Application logs
  - job_name: 'application-logs'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/logs'
    scrape_interval: 60s

  # Error tracking
  - job_name: 'error-tracking'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/errors'
    scrape_interval: 30s

  # Performance metrics
  - job_name: 'performance-metrics'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/performance'
    scrape_interval: 60s

  # User activity
  - job_name: 'user-activity'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/analytics'
    scrape_interval: 300s

  # Business metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/business'
    scrape_interval: 600s
